const types = {
  /* GENERALS TYPES */
  LOADING: 'LOADING',
  LOADING_COMPONENT: 'LOADING_COMPONENT',
  ERROR: 'ERROR',
  ERROR_COMPONENT: 'ERROR_COMPONENT',
  GET_USERS: 'GET_USERS',
  GET_POSTS: 'GET_POSTS',
  GET_COMMENTS: 'GET_COMMENTS',
  GET_TODOS: 'GET_TODOS',
  UPDATE_STATUS_TODO: 'UPDATE_STATUS_TODO',
  POST_TODO: 'POST_TODO',
  PUT_TODO: 'PUT_TODO',
  DELETE_TODO: 'DELETE_TODO',
  POST_MODAL: 'POST_MODAL',

  /* TO DO MODAL TYPES */
  NEW_TODO_ITEM: 'NEW_TODO_ITEM',
  EDIT_TODO_ITEM: 'EDIT_TODO_ITEM',
};

export default types;
